---
title: "TITLE"
author: "AUTHORS"
includes:
  in_header:
    - \usepackage{lmodern}
output:
  pdf_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 6
    toc: yes
  html_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 6
    theme: journal
---



Let's check out Mangal and see if we can get some more points
```{r}
library(rmangal)
library(igraph)
library(dplyr)
library(ggplot2)
library(gridExtra)
```

4499	4529	
```{r eval=FALSE}
#mgs <- rmangal::search_datasets("pollinator")
#mgn <- get_collection(mgs)

nodes <- mgn[[1000]]
mgn[[1]]$interactions
mgn[[1]]$network

summary(mgn)[[1]]

#save(mgn, amPol, file="data/Mangel_Wol_Query.Rda")
```

```{r}
load("data/Mangel_Wol_Query.Rda")
```

#amPol is from WOL
#mgn is from Mangel

```{r}
length(unique(amPol$network_name))
length(mgn)

#Creating global meta web from Mangal Data
output <- NULL
for(i in 1:length(mgn)){
  temp_inters <- as_long_data_frame(igraph::as.igraph(mgn[[i]]))
  temp_inters <- temp_inters %>% dplyr::select(., to_taxonomy.name, from_taxonomy.name, to_taxonomy.gbif, from_taxonomy.gbif, network_id) %>% unique()
  output <- rbind(output, temp_inters)
}

nrow(output) #Total number of interactions
```

```{r}
metaweb <- output %>% dplyr::filter(., is.na(to_taxonomy.gbif)==FALSE & is.na(from_taxonomy.gbif)==FALSE) %>% dplyr::select(., -network_id) %>% unique()
class(metaweb)
rownames(metaweb) <- 1:nrow(metaweb)

imeta <- igraph::graph_from_data_frame(metaweb, directed=F) #Create idgraph object
```

Let's drop nodes from disconnected components
```{r}
V(imeta)$component <- components(imeta)$membership
components(imeta)$csize #Largest component has 959 nodes; the rest are orders of magnitude smaller



imetaC <- delete.vertices(imeta, V(imeta)$component[V(imeta)$component!=which.max(components(imeta)$csize)]) #Removevertices that aren't included in the largest component
```




```{r}
igraph::centralization.betweenness(imetaC)
igraph::centralization.closeness(imetaC)
igraph::centralization.degree(imetaC, mode="all")
igraph::centralization.evcent(imetaC)

metaCent <- data.frame(between=igraph::centralization.betweenness(imetaC)$res,
           close=igraph::centralization.closeness(imetaC)$res,
           deg=igraph::centralization.degree(imetaC, mode="all")$res,
           eig=igraph::centralization.evcent(imetaC)$vector)
```

```{r}
pear_mat <- cor(metaCent, method="pearson", use="complete.obs")
spearmat <- cor(metaCent, method="spearman", use="complete.obs")

hist(metaCent$close)
plot(metaCent$close, metaCent$between)
plot(metaCent$close, metaCent$degree)
plot(metaCent$close, metaCent$eig)

parpl <- list()
for(j in 1:4){
parpl[[j]] <- ggplot(metaCent, aes(x=metaCent[,1], y=metaCent[,j]))+geom_point()+xlab("between")+ylab(colnames(metaCent)[j])
}
for(j in 1:4){
parpl[[j+4]] <- ggplot(metaCent, aes(x=metaCent[,2], y=metaCent[,j]))+geom_point()+xlab("close")+ylab(colnames(metaCent)[j])
}
for(j in 1:4){
parpl[[j+8]] <- ggplot(metaCent, aes(x=metaCent[,3], y=metaCent[,j]))+geom_point()+xlab("deg")+ylab(colnames(metaCent)[j])
}
for(j in 1:4){
parpl[[j+12]] <- ggplot(metaCent, aes(x=metaCent[,4], y=metaCent[,j]))+geom_point()+xlab("eig")+ylab(colnames(metaCent)[j])
}

#pdf(file="figs/PairwiseCors.pdf", width=11, height=11)
grid.arrange(parpl[[1]], 
             parpl[[2]], 
             parpl[[3]],
             parpl[[4]],
             parpl[[5]],
             parpl[[6]],
             parpl[[7]],
             parpl[[8]],
             parpl[[9]],
             parpl[[10]],
             parpl[[11]],
             parpl[[12]],
             parpl[[13]],
             parpl[[14]],
             parpl[[15]],
             parpl[[16]],
             nrow = 4)
#dev.off()


#pdf(file="figs/CentralityCorrelations.pdf", width=8, height=4)
par(mfrow = c(1, 2))
corrplot::corrplot(pear_mat, type = "lower", diag=T, main="Pearson's Correlation", mar=c(0,0,2,0), method="ellipse")
corrplot::corrplot(spearmat, type = "lower", diag=T, main="Spearman's Correlation", mar=c(0,0,2,0), method="ellipse")
#dev.off()
```





